DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTc0MzQyMzQsInVzZXJJZCI6MX0.lG0hJgblSdH4vg4Vy46Chs0UrsDuJbuIjk--fVXXrmA