POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTc0MjgyNTUsInVzZXJJZCI6MX0.SrsCDI9F2ZQXe8pPFNSJNjesnmA5PoPu_Mm-nkhhMQ0

{
    "name": "Test event",
    "description": "Test event!!!",
    "location": "A test location",
    "dateTime":"2025-01-01T15:30:00.000Z"
}
